# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428f82002f5d5d8d7a206885f3ce05cac17f1d06bece7d00b89c0116d47bf38eecd1a259582b64f271a78fe94ce10f04349c565b37dc9ca41958e5b294fc71be

test:
  secret_key_base: 00de5f05c606d3a997e9643c2867c5117797708c0d83ed31309dcdee9101e999ecafe9e4429218e1749058d956a5b9d8a234f220c6d44cd883c4d3308cfc513b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
