crypto_currencies:
  - btc
  - eth
  - eos
  - gxs
  - bch
  - usdt
  - zec
  - bcd
  - qtum
  - bnb
  - ltc
  - bnb

crypto_exchanges:
  - coinmarketcap
  - binance
  - bitoex
  - huobi
  - maicoin
  - okcoin
