crypto_currencies:
  - btc
  - eth
  - eos
  - gxs
  - bch
  - usdt
  - zec
  - bcd
  - qtum
  - bnb
  - ltc
  - bnb

crypto_exchanges:
  - coinmarketcap
  - bitoex
  - maicoin
  - binance
  - huobi
  - okcoin

fiat_currencies:
  - usd
  - twd
  - cny
  - jpy
  - krw
