crypto_currencies:
  - btc
  - ltc
  - nmc
  - trc
  - ppc
  - nvc
  - ftc
  - mnc
  - frc
  - ixc
  - btb
  - wdc
  - dgc
  - gld
  - arg
  - fst
  - btg
  - pxc
  - mec
  - ifc
  - xpm
  - anc
  - csc
  - cbx
  - emd
  - glc
  - xrp
  - qrk
  - zet
  - src
  - sxc
  - tag
  - i0c
  - flo
  - nxt
  - uno
  - xjo
  - dtc
  - bet
  - gdc
  - dem
  - doge
  - net
  - phs
  - dmd
  - hbn
  - tgc
  - orb
  - omni
  - cat
  - tips
  - rpc
  - moon
  - dime
  - 42
  - vtc
  - kdc
  - red
  - dgb
  - smc
  - tes
  - karma
  - nobl
  - rdd
  - nyan
  - utc
  - pot
  - blc
  - max
  - q2c
  - huc
  - dash
  - xcp
  - cach
  - top
  - icn
  - mint
  - ari
  - dope
  - aur
  - ani
  - ptc
  - mars
  - cash
  - ric
  - pnd
  - mzc
  - ufo
  - blk
  - ltb
  - pho
  - zeit
  - xmy
  - skc
  - emc2
  - btcs
  - cno
  - ecc
  - mona
  - rby
  - bela
  - flt
  - 888
  - fair
  - slr
  - efl
  - nlg
  - plc
  - grs
  - xpd
  - plnc
  - xwc
  - ac
  - pop
  - bits
  - qbc
  - ccn
  - sloth
  - blu
  - maid
  - xbc
  - talk
  - nyc
  - cdn
  - gun
  - pink
  - drm
  - cfc
  - enrg
  - vrc
  - tek
  - xmr
  - lcp
  - cure
  - unb
  - crypt
  - qcn
  - super
  - qora
  - bost
  - hyper
  - btq
  - moto
  - cloak
  - bsd
  - c2
  - fcn
  - bcn
  - aby
  - nav
  - uro
  - grn
  - don
  - piggy
  - start
  - kore
  - xdn
  - bbr
  - sha
  - blz
  - thc
  - brit
  - xst
  - trust
  - clam
  - qtl
  - bts
  - btcd
  - trk
  - via
  - fire
  - tri
  - sdc
  - ioc
  - xcn
  - carbon
  - cann
  - xlm
  - tit
  - vta
  - hyp
  - j
  - sys
  - btm
  - hal
  - sjcx
  - neos
  - emc
  - rbbt
  - burst
  - game
  - wsx
  - ubq
  - bun
  - opal
  - acoin
  - fldc
  - bitusd
  - bitcny
  - bitbtc
  - usnbt
  - slg
  - xmg
  - excl
  - troll
  - unity
  - bsty
  - dp
  - pxi
  - swift
  - dsh
  - au
  - stv
  - xvg
  - nsr
  - spr
  - rbt
  - mue
  - block
  - gap
  - ttc
  - crw
  - bay
  - blitz
  - gcn
  - xqn
  - byc
  - bcf
  - ok
  - xpy
  - vtr
  - bitgold
  - uis
  - gp
  - coval
  - nxs
  - soon
  - metal
  - nka
  - smly
  - amber
  - mac
  - bitsilver
  - dot
  - kobo
  - con
  - bitb
  - geo
  - usdt
  - wbb
  - grc
  - xvc
  - xco
  - sak
  - bitz
  - ldoge
  - unc
  - song
  - log
  - slfi
  - crave
  - pura
  - xem
  - 8bit
  - lea
  - ntrn
  - xaur
  - cf
  - aib
  - egg
  - sphr
  - medic
  - bub
  - muse
  - unit
  - shell
  - cto
  - pkb
  - arb
  - gam
  - bta
  - adc
  - snrg
  - biteur
  - unic
  - fjc
  - erc
  - funk
  - hxx
  - xra
  - mtlmc3
  - creva
  - irl
  - zny
  - cyc
  - bsc
  - acp
  - tagr
  - cpn
  - chc
  - sprts
  - hnc
  - cpc
  - flax
  - off
  - bios
  - manna
  - axiom
  - leo
  - aeon
  - eth
  - sjw
  - tx
  - gcc
  - ams
  - euc
  - sc
  - gcr
  - dcre
  - mad
  - shift
  - vec2
  - boli
  - space
  - fly
  - bcy
  - pak
  - infx
  - exp
  - steps
  - sib
  - isl
  - swing
  - fct
  - duo
  - sandg
  - pr
  - cube
  - rep
  - shnd
  - $pac
  - 1337
  - $$$
  - soil
  - scrt
  - dft
  - obits
  - amp
  - gbc
  - x2
  - club
  - adz
  - mnd
  - moin
  - av
  - rc
  - egc
  - opes
  - crb
  - rads
  - ltcr
  - yoc
  - sls
  - frn
  - evil
  - dcr
  - pivx
  - safex
  - hmp
  - rbies
  - adcn
  - des
  - klc
  - trump
  - meme
  - xct
  - ims
  - hodl
  - bigup
  - neva
  - bumba
  - rvr
  - pex
  - cab
  - mojo
  - gmx
  - lsk
  - edrc
  - post
  - op
  - bern
  - qwark
  - dgd
  - steem
  - fans
  - esp
  - fuzz
  - disk
  - xhi
  - arco
  - xbtc21
  - el
  - zur
  - 611
  - 2give
  - xptx
  - abc
  - lana
  - ponzi
  - tesla
  - mxt
  - nlx
  - richx
  - prm
  - waves
  - newb
  - icoo
  - ion
  - hvco
  - mnm
  - xre
  - gb
  - brk
  - dbtc
  - cmt
  - rise
  - chess
  - lbc
  - put
  - brx
  - synx
  - cj
  - ree
  - heat
  - lir
  - dlisk
  - sbd
  - lkc
  - crx
  - ardr
  - etc
  - 808
  - bit
  - poke
  - ele
  - gain
  - krb
  - vprc
  - strat
  - pres
  - aces
  - gary
  - taj
  - today
  - px
  - edr
  - bxt
  - ths
  - atx
  - aglc
  - xp
  - vlt
  - kb3
  - blockpay
  - golf
  - neo
  - jwl
  - lmc
  - btdx
  - nlc2
  - sport
  - vrm
  - zyd
  - jin
  - xto
  - plu
  - tell
  - sh
  - dlc
  - mst
  - xbts
  - proud
  - seq
  - omc
  - 1st
  - pepecash
  - icn
  - sngls
  - calc
  - xzc
  - rcn
  - atom
  - jobs
  - trig
  - skr
  - royal
  - levo
  - arc
  - qbt
  - dmc
  - zec
  - imps
  - asafe2
  - bip
  - zcl
  - zoi
  - wa
  - lkk
  - gnt
  - zmc
  - btcr
  - rega
  - bash
  - iop
  - vrs
  - hush
  - kurt
  - xcre
  - xrc
  - pasc
  - ent
  - incnt
  - dct
  - nodc
  - golos
  - nxc
  - shorty
  - vsl
  - dollar
  - vltc
  - pcs
  - tcoin
  - gbyte
  - bpc
  - posw
  - luna
  - frgc
  - wings
  - dix
  - units
  - dar
  - iflt
  - xspec
  - xstc
  - ldcn
  - benji
  - ccrb
  - vidz
  - bcc
  - icob
  - ibank
  - mkr
  - prx
  - drs
  - kmd
  - frst
  - mgm
  - tse
  - sfc
  - zbc
  - wct
  - icon
  - kush
  - lepen
  - gcc
  - acn
  - boat
  - ery
  - els
  - gbg
  - cwxt
  - cnt
  - mar
  - mscn
  - kashh
  - mln
  - all
  - prc
  - time
  - argus
  - rns
  - ur
  - swt
  - pie
  - marx
  - visio
  - nano
  - lvps
  - geert
  - pasl
  - milo
  - music
  - zer
  - biob
  - honey
  - netko
  - ark
  - dyn
  - tks
  - mer
  - taas
  - soar
  - edg
  - b@
  - zse
  - worm
  - dtb
  - best
  - uni
  - xlr
  - imx
  - tstr
  - xas
  - score
  - dbix
  - ked
  - gup
  - usc
  - ecn
  - sky
  - blazr
  - atmos
  - emv
  - inpay
  - hpc
  - zeni
  - cxt
  - xot
  - conx
  - ebt
  - fazz
  - xby
  - rlc
  - trst
  - deus
  - alt
  - wgo
  - mcrn
  - dashs
  - tle
  - proc
  - scs
  - btx
  - volt
  - lun
  - gno
  - tkn
  - rain
  - gpl
  - hmq
  - func
  - iti
  - mne
  - cnnc
  - crea
  - dice
  - insn
  - hallo
  - ant
  - pzm
  - rlt
  - qtum
  - eco
  - eqt
  - dmb
  - apx
  - mcap
  - nanox
  - may
  - sumo
  - zengold
  - bat
  - zen
  - etbs
  - ae
  - v
  - etp
  - ebst
  - adk
  - stex
  - ptoy
  - qau
  - veri
  - eca
  - qrl
  - ett
  - mgo
  - ammo
  - nro
  - ppy
  - miota
  - myst
  - lgd
  - snm
  - linx
  - zrc
  - bnt
  - cheap
  - cfi
  - glt
  - nmr
  - otx
  - unify
  - xel
  - coupe
  - mrt
  - bitok
  - hnc
  - knc
  - dcy
  - xlc
  - onx
  - btpl
  - gxs
  - good
  - antx
  - bro
  - flash
  - skull
  - fun
  - pay
  - snt
  - chan
  - efyt
  - bria
  - eos
  - turbo
  - adx
  - dnr
  - bet
  - storj
  - bnx
  - socc
  - adt
  - mco
  - ping
  - uet
  - wgr
  - slevin
  - ecob
  - unrc
  - plbt
  - gas
  - snc
  - jet
  - mtl
  - ppt
  - women
  - vuc
  - bdl
  - xid
  - daxx
  - fxe
  - rup
  - fnc
  - gtc
  - pcn
  - hero
  - san
  - omg
  - ter
  - cvcoin
  - net
  - xrl
  - linda
  - mbrs
  - cvc
  - ethos
  - btwty
  - sta
  - rsgp
  - coal
  - lbtc
  - part
  - primu
  - smart
  - skin
  - bch
  - hmc
  - toa
  - plr
  - xry
  - sigt
  - ctic2
  - oct
  - bnb
  - 300
  - pbt
  - cmpco
  - emb
  - ixt
  - gsr
  - msp
  - asn
  - birds
  - crm
  - era
  - kek
  - oax
  - dnt
  - fyn
  - stx
  - minex
  - cdt
  - wink
  - btm
  - ctr
  - mao
  - bitcf
  - ndc
  - tix
  - dcn
  - rupx
  - shdw
  - onion
  - cat
  - adst
  - ddf
  - bas
  - dent
  - mbi
  - ift
  - xcxt
  - riya
  - tcc
  - zrx
  - bln
  - smoke
  - yoyow
  - grwi
  - myb
  - hsr
  - ven
  - tfl
  - xtd
  - nas
  - atmc
  - dalc
  - prn
  - ox
  - acc
  - bbp
  - bq
  - act
  - namo
  - sigma
  - xmcc
  - tnt
  - wtc
  - brat
  - ula
  - pst
  - opt
  - sur
  - lrc
  - ltcu
  - poe
  - nto
  - strc
  - krone
  - cyder
  - mtnc
  - mth
  - avt
  - dlt
  - hvn
  - vsx
  - magn
  - mda
  - nebl
  - vivo
  - trx
  - ocl
  - rex
  - buzz
  - credo
  - drxne
  - aht
  - mana
  - ind
  - xpa
  - scl
  - atb
  - iqt
  - ethd
  - pro
  - link
  - bmc
  - wic
  - elix
  - xbl
  - knc
  - vibe
  - sub
  - day
  - chips
  - tkr
  - pix
  - coss
  - csno
  - rvt
  - kin
  - itz
  - tgt
  - salt
  - india
  - orme
  - kln
  - mci
  - colx
  - tzc
  - hdlb
  - odn
  - cob
  - rec
  - msd
  - bis
  - ada
  - xtz
  - voise
  - xin
  - atm
  - mcr
  - kick
  - ett
  - vib
  - rhoc
  - inxt
  - whl
  - flik
  - ebet
  - cnx
  - wild
  - real
  - hbt
  - cct
  - bco
  - evx
  - ppp
  - air
  - pos
  - sdrn
  - alis
  - btcz
  - hgt
  - cnd
  - eng
  - ctic3
  - bsn
  - zsc
  - ecash
  - cor
  - sic
  - ats
  - rkc
  - aky
  - exn
  - pipl
  - edo
  - ast
  - cag
  - bcpt
  - aion
  - trct
  - art
  - xgox
  - evr
  - dutch
  - otn
  - drt
  - req
  - b2x
  - etg
  - blue
  - runners
  - life
  - hdg
  - mod
  - amb
  - icos
  - btg
  - kcs
  - exrn
  - poll
  - la
  - xuc
  - nuls
  - btcred
  - prg
  - bos
  - rcn
  - xios
  - gmt
  - icx
  - js
  - elite
  - itt
  - ieth
  - pirl
  - xnn
  - lux
  - ereal
  - ntwk
  - dovu
  - rpx
  - bt2
  - placo
  - roofs
  - fap
  - btcm
  - fuel
  - ella
  - vulc
  - qvt
  - rmc
  - fyp
  - ebtc
  - btbc
  - enj
  - powr
  - grid
  - r
  - atl
  - etn
  - high
  - mnx
  - sono
  - for
  - data
  - xsh
  - pure
  - eltcoin
  - dsr
  - ukg
  - crdnc
  - nio
  - ctx
  - arn
  - stars
  - phr
  - frd
  - inn
  - rdn
  - dpy
  - zeph
  - drp
  - erc20
  - tie
  - bpl
  - grim
  - zcg
  - oxy
  - abj
  - epy
  - hold
  - neog
  - dbet
  - hst
  - sss
  - ufr
  - hat
  - stu
  - gvt
  - eagle
  - eag
  - prix
  - itns
  - plc
  - ebch
  - sisa
  - astro
  - payx
  - grx
  - aerm
  - bte
  - sgr
  - viu
  - alqo
  - gbx
  - wc
  - prl
  - b2b
  - pnx
  - xcpo
  - dgpt
  - dna
  - ink
  - bot
  - qsp
  - qash
  - zzc
  - tsl
  - pbl
  - mag
  - spank
  - vot
  - bcd
  - vee
  - ai
  - acc
  - tria
  - plx
  - divx
  - monk
  - flixx
  - gls
  - ryz
  - tnb
  - wish
  - evc
  - lend
  - ong
  - cco
  - qbt
  - drgn
  - pfr
  - pre
  - cmt
  - bcdn
  - capp
  - ero
  - mage
  - itc
  - jiyo
  - send
  - bon
  - nuko
  - snov
  - sbc
  - bwk
  - saga
  - cms
  - kbr
  - tok
  - pcoin
  - cms
  - wabi
  - crc
  - wand
  - spf
  - cred
  - sct
  - uqc
  - mds
  - pra
  - ignis
  - smt
  - hwc
  - pkt
  - fil
  - bcx
  - sbtc
  - dat
  - trdt
  - btca
  - amm
  - loc
  - wrc
  - gto
  - ytn
  - gnx
  - dav
  - ubtc
  - star
  - ost
  - storm
  - dtr
  - elf
  - wax
  - med
  - dew
  - ngc
  - brd
  - bix
  - dai
  - sphtx
  - bnty
  - ace
  - dim
  - srn
  - cpay
  - html
  - dbc
  - hbc
  - neu
  - utk
  - qlc
  - frct
  - play
  - big
  - mtx
  - mdc
  - mot
  - hpy
  - pylnt
  - ent
  - stak
  - fdx
  - cat
  - lbtc
  - gtc
  - tau
  - esc
  - blt
  - swftc
  - cov
  - can
  - appc
  - hpb
  - wicc
  - numus
  - mdt
  - xin
  - gcs
  - nms
  - cl
  - cefs
  - get
  - opc
  - cfun
  - aidoc
  - can
  - polis
  - hkn
  - show
  - stn
  - zap
  - tct
  - fair
  - aix
  - rebl
  - ins
  - god
  - utt
  - cdx
  - tio
  - bdg
  - qun
  - topc
  - lev
  - krm
  - kcash
  - atn
  - sxdt
  - sxut
  - swtc
  - vzt
  - cld
  - ucom
  - bca
  - ugc
  - bkx
  - eko
  - bto
  - awr
  - tel
  - ic
  - weth
  - hac
  - key
  - int
  - rnt
  - gjc
  - sense
  - moac
  - tokc
  - iost
  - idt
  - ait
  - qube
  - edt
  - spc
  - ore
  - hc
  - horse
  - rct
  - arct
  - theta
  - mvc
  - put
  - nox
  - ipl
  - idxm
  - aura
  - agi
  - gat
  - sexc
  - chat
  - ddd
  - mobi
  - hot
  - bar
  - stc
  - ipc
  - mag
  - light
  - ref
  - yee
  - aac
  - ssc
  - read
  - mof
  - tnc
  - c20
  - ary
  - dta
  - crpt
  - spk
  - cv
  - tbx
  - ekt
  - uip
  - prs
  - of
  - true
  - ocn
  - idh
  - qbic
  - guess
  - aid
  - eve
  - bpt
  - axp
  - trac
  - let
  - zil
  - meet
  - slt
  - fota
  - soc
  - man
  - grlc
  - ruff
  - nkc
  - cofi
  - eql
  - hlc
  - zpt
  - cpc
  - oc
  - hmc
  - candy
  - sms
  - epc
  - vlc
  - btw
  - cxo
  - trf
  - ela
  - stk
  - pareto
  - poly
  - mtn
  - jnt
  - chsb
  - zla
  - adb
  - ht
  - dmt
  - ing
  - blz
  - swm
  - tky
  - drpu
  - esz
  - dxt
  - wpr
  - ucash
  - mntp
  - jew
  - acc
  - mlm
  - avh
  - loci
  - indi
  - jc
  - bio
  - sup
  - tig
  - utnp
  - acat
  - evn
  - rmt
  - dth
  - cas
  - fsn
  - w3c
  - ech
  - mwat
  - gla
  - dadi
  - ntk
  - gem
  - ren
  - lcc
  - stq
  - tdx
  - cpy
  - ncash
  - abt
  - rem
  - exy
  - poa
  - xnk
  - rkt
  - bez
  - iht
  - rfr
  - lym
  - seth
  - cs
  - bee
  - instar
  - auto
  - ezt
  - tube
  - ledu
  - tusd
  - hqx
  - stac
  - ont
  - datx
  - j8t
  - chp
  - tomo
  - grft
  - bax
  - elec
  - btcp
  - ten
  - rvn
  - tfd
  - ship
  - ldc
  - shp
  - lala
  - occ
  - deb
  - cennz
  - hav
  - fluz
  - loom
  - getx
  - hire
  - drop
  - banca
  - drg
  - latx
  - nanj
  - ckusd
  - up
  - bbn
  - noah
  - lgo
  - 1wo
  - npx
  - npxs
  - bitg
  - bft
  - wan
  - amlt
  - mith
  - lst
  - pcl
  - sig
  - rntb
  - tbar
  - xbp
  - lnc
  - spd
  - ipsx
  - scc
  - bstn
  - swth
  - sen
  - clr
  - senc
  - vit
  - fdz
  - tpay
  - berry
  - xtl
  - nct
  - ode
  - xmo
  - xsn
  - xdce
  - tds
  - bbi
  - fid
  - ctxc
  - atc
  - win
  - cpx
  - cvt
  - sent
  - eosdac
  - uuu
  - adh
  - snip
  - bsm
  - dev
  - cbt
  - grmd
  - cvh
  - auc
  - bubo
  - xmc
  - dan
  - brm
  - mfg
  - dig
  - adi
  - trio
  - xhv
  - kst
  - crc
  - dero
  - efx
  - ftx
  - earth
  - mrk
  - pxc
  - crop
  - srcoin
  - chx
  - msr
  - dock
  - phi
  - lnc
  - bbc
  - dml
  - hbz
  - ori
  - hot
  - trak
  - aph
  - zco
  - lnd
  - xes
  - vips
  - rblx
  - btrn
  - pnt
  - nbai
  - lrn
  - nexo
  - vme
  - dax
  - hade
  - hydro
  - ss
  - ttt
  - bci
  - betr
  - tns
  - amn
  - plan
  - cmct
  - mitx
  - live
  - mtc
  - mt
  - key
  - nty
  - cjt
  - bouts
  - pal
  - cre
  - gene
  - apr
  - ac3
  - fxt
  - zipt
  - skm
  - gen
  - bznt
  - team
  - frv
  - oot
  - atx
  - frec
  - edu
  - cnn
  - insur
  - gsc
  - sgcc
  - dgx
  - inc
  - iic
  - skb
  - bank
  - nper

crypto_exchanges:
  - coinmarketcap
  - poloniex
  - bitoex
  - maicoin
  - binance
  - huobi
  - okcoin

fiat_currencies:
  - usd
  - twd
  - cny
  - jpy
  - krw
